apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleoverloadapi
  labels:
    app: simpleoverloadapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleoverloadapi
  template:
    metadata:
      labels:
        app: simpleoverloadapi
    spec:
      containers:
      - name: simpleoverloadapi
        image: jacquesrockell/simpleoverloadapi:1.6
        
        resources:
          limits: 
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: DB_CONNECTION
            value: "mongodb+srv://jacquesrockell:v2hCKdZRd6kwpMN@jrcluster0.wd77u.mongodb.net/SimpleOverload?retryWrites=true&w=majority"
          - name: TOKEN_SECRET
            value: "tsasd"
---

apiVersion: v1
kind: Service
metadata:
  name: simpleoverloadapi-service
spec:
  type: ClusterIP
  selector:
    app: simpleoverloadapi
  ports:
    - port: 80
      targetPort: 8080